// apps/vue/src/App.vue
<template>
  <div class="main">
    <div class="description">
      <button @click="toggleSpace">{{ showSpace ? 'Close' : 'Open' }} space</button>
    </div>
    <div v-if="showSpace" class="space-wrapper">
      <UseSpace v-bind="spaceProps" />
    </div>
  </div>
</template>

<script>
import { ref } from 'vue';
import { UseSpace } from '@flatfile/vue';
import { config } from "./config";

const SPACE_ID = 'us_sp_1234';
const ENVIRONMENT_ID = 'us_env_1234';

export default {
  setup() {
    const showSpace = ref(false);
    const publishableKey = 'your_key';
    const environmentId = ENVIRONMENT_ID;
    const spaceProps = ref({
      name: 'Trste!',
      environmentId,
      publishableKey,
      closeSpace: {
        operation: 'contacts:submit',
        onClose: () => { showSpace.value = false; },
      },
      workbook: config,
      themeConfig: { primaryColor: "#546a76", textColor: "#fff" },
      userInfo: {
        name: 'my space name'
      },
      spaceInfo: {
        name: 'my space name'
      },
      displayAsModal: true,
      spaceBody: {
        metadata: {
          random: 'param'
        }
      }
    });

    const toggleSpace = () => {
      showSpace.value = !showSpace.value;
    };

    return {
      showSpace,
      toggleSpace,
      spaceProps,
    };
  },
  components: {
    UseSpace
  },
};
</script>

// apps/react/app/App.tsx
'use client'
import React, { useState } from 'react'
import { useSpaceTrigger } from '@flatfile/react'
import { listener } from './listener'
import styles from './page.module.css'
import { config } from './config'

const SPACE_ID = 'us_sp_123456'
const ENVIRONMENT_ID = 'us_env_O60vqdol'

const spaceProps = {
  environmentId: ENVIRONMENT_ID,
  iframeStyles: {
    borderRadius: '12px',
    width: '100%',
    height: '750px',
    borderWidth: ' 0px',
    background: 'rgb(255, 255, 255)',
    padding: '16px',
  },
  listener: listener,
  publishableKey: "pk_3626978e5f52480085a37844166d347a",
  workbook: config
}

const LoadingComponent = () => <label>Loading data....</label>

function App() {
  const [showSpace, setShowSpace] = useState(false)
  
  const { Space, createOrUseSpace } = useSpaceTrigger({
    ...spaceProps,
    loading: <LoadingComponent />,
    exitPrimaryButtonText: 'CLOSE!',
    exitSecondaryButtonText: 'KEEP IT!',
    closeSpace: {
      operation: 'contacts:submit',
      onClose: () => setShowSpace(false),
    },
  })

  return (
    <div className={styles.main}>
      <div className={styles.description}>
        <button
          onClick={async () => {
            setShowSpace(!showSpace)
            await createOrUseSpace()
          }}
        >
          {showSpace === true ? 'Close' : 'Open'} space
        </button>
      </div>
      {showSpace && (
        <div className={styles.spaceWrapper}>
          <Space />
        </div>
      )}
    </div>
  )
}

export default App
