// apps/vue/src/App.vue
<template>
  <div class="main">
    <div class="description">
      <button @click="toggleSpace">{{ showSpace ? 'Close' : 'Open' }} space</button>
    </div>
    <div v-if="showSpace" class="space-wrapper">
      <UseSpace v-bind="spaceProps" />
    </div>
  </div>
</template>

<script>
import { ref } from 'vue';
import { UseSpace } from '@flatfile/vue';
import { config } from "./config";

const SPACE_ID = 'us_sp_1234';
const ENVIRONMENT_ID = 'us_env_1234';

export default {
  setup() {
    const showSpace = ref(false);
    const publishableKey = 'your_key';
    const environmentId = ENVIRONMENT_ID;
    const spaceProps = ref({
      name: 'Trste!',
      environmentId,
      publishableKey,
      closeSpace: {
        operation: 'contacts:submit',
        onClose: () => { showSpace.value = false; },
      },
      workbook: config,
      themeConfig: { primaryColor: "#546a76", textColor: "#fff" },
      userInfo: {
        name: 'my space name'
      },
      spaceInfo: {
        name: 'my space name'
      },
      displayAsModal: true,
      spaceBody: {
        metadata: {
          random: 'param'
        }
      }
    });

    const toggleSpace = () => {
      showSpace.value = !showSpace.value;
    };

    return {
      showSpace,
      toggleSpace,
      spaceProps,
    };
  },
  components: {
    UseSpace
  },
};
</script>

// packages/react/src/App.tsx
import React, { useState } from 'react'
import ReactDOM from 'react-dom'
import { ISpace } from './types/ISpace'
import { makeTheme } from './utils/makeTheme'
import { useSpace } from './hooks/useSpace'
import { listener, config } from './examples/joinFields'

const spaceProps: ISpace = {
  name: 'Embedded Space',
  // to test locally add your local vars here
  publishableKey: '',
  environmentId: '',
  workbook: config,
  themeConfig: makeTheme({ primaryColor: '#546a76', textColor: '#fff' }),
  sidebarConfig: {
    showDataChecklist: false,
    showSidebar: false
  },
  listener
}

const ExampleApp = () => {
  const [showSpace, setShowSpace] = useState(false)

  const { component } = useSpace({
    ...spaceProps,
    closeSpace: {
      operation: 'contacts:submit',
      onClose: () => setShowSpace(false)
    }
  })

  return (
    <div style={{ padding: '16px' }}>
      <button
        onClick={() => {
          setShowSpace(!showSpace)
        }}
      >
        {showSpace === true ? 'Close' : 'Open'} space
      </button>
      {showSpace && component}
    </div>
  )
}

const root = document?.getElementById('root')

ReactDOM.render(<ExampleApp />, root)
