// packages/react/src/hooks/useSpace.tsx
import React, { JSX, useEffect, useState } from 'react'
import DefaultError from '../components/Error'
import Space from '../components/Space'
import Spinner from '../components/Spinner'
import { SpinnerStyles } from '../components/embeddedStyles'
import { ISpace, State } from '@flatfile/embedded-utils'
import { initializePubnub } from '../utils/initializePubnub'
import { initializeSpace } from '../utils/initializeSpace'
import { getSpace } from '../utils/getSpace'


export const useSpace = (props: ISpace): JSX.Element => {
  const { error: ErrorElement, errorTitle, loading: LoadingElement, apiUrl } = props
  const [initError, setInitError] = useState<Error | string>()
  const [state, setState] = useState<State>({
    pubNub: null,
    localSpaceId: '',
    accessTokenLocal: '',
    spaceUrl: '',
  })

  const { localSpaceId, pubNub, spaceUrl, accessTokenLocal } = state

  const initSpace = async () => {
    try {
      const { data } = props.publishableKey
        ? await initializeSpace(props)
        : await getSpace(props)

      if (!data) {
        throw new Error('Failed to initialize space')
      }

      const { id: spaceId, accessToken, guestLink } = data

      if (!spaceId) {
        throw new Error('Missing spaceId from space response')
      }

      if (!guestLink) {
        throw new Error('Missing guest link from space response')
      }

      setState((prevState) => ({
        ...prevState,
        localSpaceId: spaceId,
        spaceUrl: guestLink,
      }))

      if (!accessToken) {
        throw new Error('Missing access token from space response')
      }

      setState((prevState) => ({
        ...prevState,
        accessTokenLocal: accessToken,
      }))

      const initializedPubNub = await initializePubnub({
        spaceId,
        accessToken,
        apiUrl
      })

      setState((prevState) => ({
        ...prevState,
        pubNub: initializedPubNub,
      }))
    } catch (error: any) {
      setInitError(error)
    }
  }

  useEffect(() => {
    initSpace()
  }, [])

  const errorElement = ErrorElement ? (
    // Adding non-null assertion because this will never be hit if error is falsy, ts is unhappy.
    ErrorElement(initError!)
  ) : (
    <DefaultError error={errorTitle || initError!} />
  )

  const loadingElement = LoadingElement ?? (
    <SpinnerStyles>
      <Spinner />
    </SpinnerStyles>
  )

  if (initError) {
    return errorElement
  }

  if (pubNub) {
    return (
      <Space
        spaceId={localSpaceId}
        spaceUrl={spaceUrl}
        accessToken={accessTokenLocal}
        pubNub={pubNub}
        {...props}
      />
    )
  }

  return loadingElement
}

export default useSpace

// packages/vue/src/components/UseSpace.vue
<template>
  <div>
    <DefaultError v-if="initError" :error="initError" />
    <SpaceC
      v-if="spaceUrl && pubNub"
      :pubNub="pubNub"
      :spaceId="localSpaceId"
      :spaceUrl="spaceUrl"
      :accessToken="accessTokenLocal"
      :apiUrl="apiUrl"
      :displayAsModal="displayAsModal"
      :exitText="exitText"
      :exitTitle="exitTitle"
      :workbook="workbook"
      :exitPrimaryButtonText="exitPrimaryButtonText"
      :exitSecondaryButtonText="exitSecondaryButtonText"
      :closeSpace="closeSpace"
      :listener="listener"
      :sidebarConfig="sidebarConfig"
      :spaceInfo="spaceInfo"
      :userInfo="userInfo"
      :document="document"
      :themeConfig="themeConfig"
      :environmentId="environmentId"
      :iframeStyles="iframeStyles"
    />
    <SpinnerC v-else></SpinnerC>
  </div>
</template>

<script>
import { ref, onMounted } from 'vue';
import useInitializeSpace from '../utils/useInitializeSpace';
import getSpace from '../utils/getSpace';
import { initializePubnub } from '@flatfile/embedded-utils'
import SpaceC from './SpaceC.vue';
import SpinnerC from './Spinner.vue';
import DefaultError from './DefaultError.vue';

export default {
  props: {
    name: String,
    publishableKey: String,
    environmentId: String,
    closeSpace: Object,
    space: Object,
    themeConfig: Object,
    listener: Object,
    sidebarConfig: Object,
    document: Object,
    spaceBody: Object,
    spaceInfo: Object,
    userInfo: Object,
    workbook: Object,
    displayAsModal: Boolean,
    iframeStyles: Object,
    mountElement: {
      type: String,
      default: 'flatfile_iFrameContainer',
    },
    exitText: {
      type: String,
      default: 'Are you sure you want to exit? Any unsaved changes will be lost.',
    },
    exitTitle: {
      type: String,
      default: 'Close Window',
    },
    exitPrimaryButtonText: {
      type: String,
      default: 'Yes, exit',
    },
    exitSecondaryButtonText: {
      type: String,
      default: 'No, stay',
    },
    apiUrl: {
      type: String,
      default: 'https://platform.flatfile.com/api',
    },
  },
  setup(props) {
    const { space, initializeSpace } = useInitializeSpace(props);
    const initError = ref(null);
    const localSpaceId = ref(null);
    const pubNub = ref(null);
    const accessTokenLocal = ref(null);
    const spaceUrl = ref('');

    const initSpace = async () => {
      try {
        const data = props.publishableKey
          ? await initializeSpace(props)
          : await getSpace(props);
          
        if (!data) {
          throw new Error('Failed to initialize space');
        }
        
        const { id: spaceId, accessToken, guestLink } = data.data;

        if (!spaceId) {
          throw new Error('Missing spaceId from space response');
        }

        if (!guestLink) {
          throw new Error('Missing guest link from space response');
        }

        if (!accessToken) {
          throw new Error('Missing access token from space response');
        }

        const initializedPubNub = await initializePubnub({
          spaceId,
          accessToken,
          apiUrl: props.apiUrl,
        });

        localSpaceId.value = spaceId;
        spaceUrl.value = guestLink;
        accessTokenLocal.value = accessToken
        pubNub.value = initializedPubNub;
      } catch (error) {
        initError.value = error.message;
      }
    };

    onMounted(() => {
      initSpace();
    });

    return {
      initSpace,
      initError,
      localSpaceId,
      spaceUrl,
      pubNub,
      accessTokenLocal,
    };
  },
  components: {
    SpaceC,
    SpinnerC,
    DefaultError
  },
};
</script>

<style lang="scss">
@import url(./../style.scss);
</style>
