// apps/vue/src/App.vue
<template>
  <div class="main">
    <div class="description">
      <button @click="toggleSpace">{{ showSpace ? 'Close' : 'Open' }} space</button>
    </div>
    <div v-if="showSpace" class="space-wrapper">
      <UseSpace v-bind="spaceProps" />
    </div>
  </div>
</template>

<script>
import { ref } from 'vue';
import { UseSpace } from '@flatfile/vue';
import { workbook } from "./config";
import { listener } from './listener'

const SPACE_ID = 'us_sp_1234';
const ENVIRONMENT_ID = 'us_env_1234';

export default {
  setup() {
    const showSpace = ref(false);
    const publishableKey = 'your_key';
    const environmentId = ENVIRONMENT_ID;
    const spaceProps = ref({
      name: 'Trste!',
      environmentId,
      publishableKey,
      closeSpace: {
        operation: 'submitActionFg',
        onClose: () => { showSpace.value = false; },
      },
      workbook,
      listener,
      themeConfig: { primaryColor: "#546a76", textColor: "#fff" },
      userInfo: {
        name: 'my space name'
      },
      spaceInfo: {
        name: 'my space name'
      },
      displayAsModal: true,
      spaceBody: {
        metadata: {
          random: 'param'
        }
      }
    });

    const toggleSpace = () => {
      showSpace.value = !showSpace.value;
    };

    return {
      showSpace,
      toggleSpace,
      spaceProps,
    };
  },
  components: {
    UseSpace
  },
};
</script>

// packages/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { ISpace, SpaceService } from '@flatfile/angular'
import { workbook } from "./workbook";
import { listener } from "./listener";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  showSpace: boolean = false;

  constructor(private spaceService: SpaceService) {}

  toggleSpace() {
    this.spaceService.OpenEmbed()
    this.showSpace = !this.showSpace;
  }

  closeSpace() {
    this.showSpace = false
  }

  spaceProps: ISpace = {
    name: 'Trste!',
    environmentId: 'us_env_1234',
    publishableKey: 'pk_1234',
    workbook,
    listener,
    closeSpace: {
      operation: 'submitActionFg',
      onClose: this.closeSpace.bind(this),
    },
    userInfo: {
      name: 'my space name',
    },
    spaceInfo: {
      name: 'my space name',
    },
    displayAsModal: false,
    spaceBody: {
      metadata: {
        random: 'param',
      },
    },
  }
}

<div class="main">
  <div class="description">
    <button (click)="toggleSpace()">
      {{ showSpace ? 'Close' : 'Open' }} space
    </button>
  </div>
  <div class="spaceWrapper" *ngIf="showSpace">
    <flatfile-space [spaceProps]="spaceProps"></flatfile-space>
  </div>
</div>
